# Generated by Django 4.2.10 on 2026-01-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('feature', 'Фича'), ('bug', 'Баг'), ('tech_debt', 'Технический долг'), ('documentation', 'Документация')], max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Критичный'), ('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Маленький')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('selected', 'Выбран'), ('in_progress', 'В прогрессе'), ('ready_to_acceptance', 'Готово к принятию'), ('closed', 'Закрыто')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
